aggMethod: max
andMethod: min
defuzzMethod: centroid
impMethod: min
input:
- mf:
  - name: mf4
    params: [-1.5, -1.0, 0.0]
  - name: mf5
    params: [-1.0, -0.25, 0.0]
  - name: mf6
    params: [-0.5, 0.0, 0.5]
  - name: mf7
    params: [0.0, 0.25, 1.0]
  - name: mf8
    params: [0.0, 1.0, 1.0]
  name: input1
- mf:
  - name: mf1
    params: [-1.5, -1.0, -0.0]
  - name: mf2
    params: [-1.0, -0.25, 0.0]
  - name: mf3
    params: [-0.5, 0.0, 0.5]
  - name: mf4
    params: [0.0, 0.25, 1.0]
  - name: mf5
    params: [0.0, 1.0, 1.5]
  name: input2
name: lezl2
orMethod: max
output:
- mf:
  - name: mf1
    params: [-1.5, -1.0, -0.5]
  - name: mf2
    params: [-1.0, -0.5, 0.0]
  - name: mf3
    params: [-0.5, 0.0, 0.5]
  - name: mf4
    params: [0.0, 0.5, 1.0]
  - name: mf5
    params: [0.5, 1.0, 1.5]
  name: output1
rules:
- [0, 0, 4, 1, 0]
- [0, 1, 4, 1, 0]
- [0, 2, 3, 1, 0]
- [0, 3, 3, 1, 0]
- [0, 4, 2, 1, 0]
- [1, 0, 4, 1, 0]
- [1, 1, 3, 1, 0]
- [1, 2, 3, 1, 0]
- [1, 3, 2, 1, 0]
- [1, 4, 1, 1, 0]
- [2, 0, 3, 1, 0]
- [2, 1, 3, 1, 0]
- [2, 2, 2, 1, 0]
- [2, 3, 1, 1, 0]
- [2, 4, 1, 1, 0]
- [3, 0, 3, 1, 0]
- [3, 1, 2, 1, 0]
- [3, 2, 1, 1, 0]
- [3, 3, 1, 1, 0]
- [3, 4, 0, 1, 0]
- [4, 0, 2, 1, 0]
- [4, 1, 1, 1, 0]
- [4, 2, 1, 1, 0]
- [4, 3, 0, 1, 0]
- [4, 4, 0, 1, 0]
type: mamdani
